version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tickets-rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER = guest
      - RABBITMQ_DEFAULT_PASS = guest
    restart: "always"
  #db:
  #  image: postgres
  #  restart: always
  #  ports:
  #    - "5432:5432"
  #  environment:
  #    POSTGRES_USERNAME: postgres
  #    POSTGRES_PASSWORD: password
  #    POSTGRES_DB: tickets