INSERT INTO SERVICE (ID, DESCRIPTION,STORE_ID,PARENT_SERVICE_ID,LEAF)
VALUES (1, 'ROOT', 1, NULL, false );

INSERT INTO SERVICE (ID, DESCRIPTION,STORE_ID,PARENT_SERVICE_ID,LEAF)
VALUES (2, 'VACINAS', 1, 1, true );

INSERT INTO SERVICE (ID, DESCRIPTION,STORE_ID,PARENT_SERVICE_ID,LEAF)
VALUES (3, 'CONSULTAS', 1, 1, true );

INSERT INTO SERVICE (ID, DESCRIPTION,STORE_ID,PARENT_SERVICE_ID,LEAF)
VALUES (4, 'EXAMES', 1, 1, false );

INSERT INTO SERVICE (ID, DESCRIPTION,STORE_ID,PARENT_SERVICE_ID,LEAF)
VALUES (5, 'IMAGEM', 1, 4, false );

INSERT INTO SERVICE (ID, DESCRIPTION,STORE_ID,PARENT_SERVICE_ID,LEAF)
VALUES (6, 'RESSONANCIA MAGNÉTICA', 1, 5, true );

INSERT INTO SERVICE (ID, DESCRIPTION,STORE_ID,PARENT_SERVICE_ID,LEAF)
VALUES (7, 'ABDOMEN TOTAL', 1, 5, true );